# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: ['_site', 'vendor']

# Site settings
title: sense home
email: sense@domain.com
description: playlists - music - hardware - software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aleksandrgilfanov.github.io"
twitter_username: gilfanov_a
github_username:  aleksandrgilfanov

# Build settings
markdown: kramdown

show_excerpts: true
theme: jekyll-theme-midnight
