#!/bin/sh -e

FILESDIR="$1"

MP3DIR="./mp3"
POSTDIR="./_posts"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%T)
YEAR=$(date +%Y)

if [ $# -eq 0 ]; then
	echo $0 {two-sample-files-dir}
	exit 0
fi

# define last number in this year, if no posts yet - use 0
LAST=0
cd $POSTDIR
for F in $YEAR-*two-samples*
do
    NAME=`basename $F .markdown`
    LAST=`echo $NAME | cut -d"-" -f6`
done
cd ..

# new post number and filename
NUM=$(printf %02d $(echo $LAST + 1 | bc))
POST="$DATE-two-samples-$NUM.markdown"

echo Copying files...
cp -v $FILESDIR/sample-${YEAR}-${NUM}-* $MP3DIR
cp -v $FILESDIR/track-${YEAR}-${NUM}-* $MP3DIR

echo Creating post $POST...
cat << EOF > $POSTDIR/$POST
---
layout: post
title:  "two samples challenge $NUM"
date:   $DATE $TIME +0300
author: Aleksandr Gilfanov
categories: news
excerpt_separator: <!--more-->
---
Two Sample Challenge $NUM by
[Me](https://github.com/aleksandrgilfanov) and
[Aleksandr Karabatov](https://github.com/elektron314)

You have only one hour to make a track using only two samples.
<!--more-->

Sense sample:

/mp3/sample-$YEAR-$NUM-sense.mp3

El sample:

/mp3/sample-$YEAR-$NUM-el.mp3

Sense track:

/mp3/track-$YEAR-$NUM-sense.mp3

El track:

/mp3/track-$YEAR-$NUM-el.mp3
EOF

echo Creating commit...
git add $POSTDIR/$POST
git add $MP3DIR/sample-$YEAR-$NUM-*
git add $MP3DIR/track-$YEAR-$NUM-*
git commit -m "Add two samples challenge $NUM"

echo Done
